close all
for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'surfDofs',  ...
                     'yname',           'surfaceError', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'loglog', ... 
                     'lineStyle',       '*-', ... 
                     'xLoopName',       'M', ...
                     'subFolderName',   '../results/FEBE_IL', ...
                     'legendEntries',   {{'method','degree','coreMethod','BC'}}, ...
                     'noXLoopPrms',     1); 

    figure(2)
    printResultsToTextFiles(study,options)
%     
%     figure(3)
%     options.yname = 'L2Error';
%     printResultsToTextFiles(study,options)
% 
%     options.xname = 'tot_time';
%     figure(3)
%     printResultsToTextFiles(study,options)
% 
%     options.xname = 'nepw';
%     figure(4)
%     printResultsToTextFiles(study,options)
end