% close all
% for study_i = 1:numel(studies)
%     study = studies(study_i);
%     options = struct('xname',           'extraGP',  ...
%                      'yname',           'surfaceError', ...
%                      'plotResults', 	1, ... 
%                      'printResults',	1, ... 
%                      'axisType',        'loglog', ... 
%                      'lineStyle',       '*-', ... 
%                      'xLoopName',       'extraGP', ...
%                      'subFolderName',   '../results/Cube', ...
%                      'legendEntries',   {{'method','formulation','degree','delta'}}, ...
%                      'noXLoopPrms',     1); 
% 
%     figure(2)
%     printResultsToTextFiles(study,options)
% end

for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'alpha',  ...
                     'yname',           'TS', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'plot', ... 
                     'lineStyle',       '-', ... 
                     'subFolderName',   '../results/Cube', ...
                     'legendEntries',   {{'method','extraGP','formulation','M','degree','delta'}}, ...
                     'noXLoopPrms',     0); 

    options.xScale = 180/pi;
    figure(4)
    printResultsToTextFiles(study,options)
end