
for study_i = 1:numel(studies)
    study = studies(study_i);
    options = struct('xname',           'agpBEM',  ...
                     'yname',           'surfaceError', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'semilogy', ... 
                     'lineStyle',       '*-', ... 
                     'xLoopName',       'agpBEM', ...
                     'subFolderName',   '../results/Simpson_Torus_gp', ...
                     'legendEntries',   {{'extraGP','extraGPBEM','M','degree','formulation'}}, ...
                     'noXLoopPrms',     1); 

    figure(2)
    printResultsToTextFiles(study,options)
end
