close all
for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'alpha',  ...
                     'yname',           'TS', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'plot', ... 
                     'lineStyle',       '-', ... 
                     'xLoopName',       'N', ...
                     'subFolderName',   '../results/M4/', ...
                     'legendEntries',   {{'M','parm','f','method','formulation'}}, ...
                     'noXLoopPrms',     0); 

    options.xScale = 180/pi;
    figure(5)
    printResultsToTextFiles(study,options)
end


temp = importdata('../../../FFI/BeTSSiIIb/NTNUFFI results/M4_HWBC_MS_AS_E30_F3.txt', ',', 7);
x = temp.data(:,1);
y = temp.data(:,2);
plot(x,y,'DisplayName','old')