function nurbs = getCEData(varargin)
options = struct('R', 1,...
                 'parm', 2); 
if nargin > 0
    if numel(varargin) > 1
        newOptions = varargin;
    else
        newOptions = varargin{1};
    end
    options = updateOptions(options,newOptions);
end
R = options.R;

qd = getQuarterDiskData('R',R,'parm',options.parm);
os = getOctSphereData(options);
nurbs = [qd, ...
         rotateNURBS(qd,'rotAxis',[1,1,1],'theta',2*pi/3), ...
         rotateNURBS(qd,'rotAxis',[1,1,1],'theta',4*pi/3), ...
         rotateNURBS(os,'rotAxis',[0,0,1],'theta',pi/2), ...
         rotateNURBS(os,'rotAxis',[0,0,1],'theta',pi), ...
         rotateNURBS(os,'rotAxis',[0,0,1],'theta',3*pi/2), ...
         rotateNURBS(os,'rotAxis',[0,1,0],'theta',pi), ...
         rotateNURBS(rotateNURBS(os,'rotAxis',[0,1,0],'theta',pi),'rotAxis',[0,0,1],'theta',pi/2), ...
         rotateNURBS(rotateNURBS(os,'rotAxis',[0,1,0],'theta',pi),'rotAxis',[0,0,1],'theta',pi), ...
         rotateNURBS(rotateNURBS(os,'rotAxis',[0,1,0],'theta',pi),'rotAxis',[0,0,1],'theta',3*pi/2)];

nurbs = makeUniformNURBSDegree(nurbs);



