function layer = setM5Parameters()

layer{1} = struct('media', 'fluid', ...
                  'R', 0.6/2, ...
                  'L', 4.8, ...
                  'l', 1, ...
                  'c_f', 1500, ...
                  'rho', 1000);