function layer = setM2Parameters(noDomains)
if nargin < 1
    noDomains = 1;
end

layer{1} = struct('media', 'fluid', ...
                  'theta1', 60*pi/180, ...
                  'theta2', 30*pi/180, ...
                  't', 0.02, ... % 0.02
                  'R', 3, ...
                  'L', 40, ...
                  'c_f', 1500, ...
                  'rho', 1000);
layer{2} = struct('media', 'solid', ...
                  'E', 210e9, ...
                  'nu', 0.3, ...
                  'rho', 7850);
layer{3} = struct('media', 'fluid', ...
                  'c_f', 340, ...
                  'rho', 1.2);

layer = layer(1:noDomains);
