function strain = calculateStrainVectorVec(dUdx, dUdy, dUdz)

if nargin == 2
    strain = [dUdx(:,1),...
              dUdy(:,2),...
              dUdy(:,1) + dUdx(:,2)];
else
    strain = [dUdx(:,1),...
              dUdy(:,2),...
              dUdz(:,3),...
              dUdz(:,2) + dUdy(:,3),...
              dUdx(:,3) + dUdz(:,1),...
              dUdy(:,1) + dUdx(:,2)];
end
          