close all

for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'alpha',  ...
                     'yname',           'TS', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'plot', ... 
                     'lineStyle',       '-', ... 
                     'xLoopName',       'N', ...
                     'xScale',       	180/pi, ...
                     'subFolderName',   '../results/M5', ...
                     'legendEntries',   {{'method','M'}}, ...
                     'noXLoopPrms',     0); 
    figure(4)
    printResultsToTextFiles(study,options)
end


