
for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'f',  ...
                     'yname',           'TS', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'plot', ... 
                     'lineStyle',       '-', ... 
                     'xLoopName',       'k', ...
                     'subFolderName',   'results/M3_sweep/', ...
                     'legendEntries',   {{'method','coreMethod','formulation','M','degreeElev','f','N'}}, ...
                     'noXLoopPrms',     1); 

    options.xScale = 180/pi;
    figure(5)
    printResultsToTextFiles(study,options)
end