close all
for study_i = 1:9 %numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'k',  ...
                     'yname',           'TS', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'plot', ... 
                     'lineStyle',       '-', ... 
                     'xLoopName',       'f', ...
                     'xScale',          5.075, ...
                     'fileDataHeaderX', 'kR_0', ...
                     'subFolderName',   '../results/articleIGA_IL_sweep', ...
                     'legendEntries',   {{'BC','method','coreMethod','degreeElev','M'}}, ...
                     'noXLoopPrms',     1); 

    figure(2)
    printResultsToTextFiles(study,options)

    options.yname = 'energyError';
    options.axisType = 'semilogy';

    figure(5)
    printResultsToTextFiles(study,options)
end