close all
for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'dofs',  ...
                     'yname',           'H1Error', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'loglog', ... 
                     'lineStyle',       '*-', ... 
                     'xLoopName',       'M', ...
                     'subFolderName',   '../results/articleIGA_convergenceAnalysis', ...
                     'legendEntries',   {{'method','degree','coreMethod','BC'}}, ...
                     'noXLoopPrms',     1); 

    figure(2)
    printResultsToTextFiles(study,options)

    options.xname = 'tot_time';
    figure(3)
    printResultsToTextFiles(study,options)

    options.xname = 'nepw';
    figure(4)
    printResultsToTextFiles(study,options)

    options.xname = 'h_max';
    figure(5)
    printResultsToTextFiles(study,options)
end