close all
for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'alpha',  ...
                     'yname',           'TS', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'plot', ... 
                     'lineStyle',       '-', ... 
                     'xLoopName',       'N', ...
                     'subFolderName',   '../results/PhD_M1/', ...
                     'legendEntries',   {{'method','coreMethod','formulation','M','N','f'}}, ...
                     'noXLoopPrms',     0); 

    options.xScale = 180/pi;
    figure(5)
    printResultsToTextFiles(study,options)
end

temp = readtable('../results/PhD_M1/M1_BEM_IGA_GBM_M6_NNaN_f1000_TSVSalpha','FileType','text', 'HeaderLines',11);
x = temp.Var1;
y = temp.Var2;
plot(x,y,'DisplayName','BEM')
legend('off');
legend('show');
