
for study_i = 1:numel(studies)
    study = studies(study_i);
    options = struct('xname',           'extraGPBEM',  ...
                     'yname',           'surfaceError', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'semilogy', ... 
                     'lineStyle',       '*-', ... 
                     'xLoopName',       'extraGPBEM', ...
                     'subFolderName',   '../results/Simpson_Torus_gp', ...
                     'legendEntries',   {{'extraGP','agpBEM','M','degree','formulation','useNeumanProj'}}, ...
                     'noXLoopPrms',     1); 

    figure(2)
    printResultsToTextFiles(study,options)
end
