close all
for study_i = 1:numel(studies)  
    study = studies(study_i);
    options = struct('xname',           'alpha',  ...
                     'yname',           'TS', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'plot', ... 
                     'lineStyle',       '-', ... 
                     'xLoopName',       'N', ...
                     'subFolderName',   '../results/PhD_M1/', ...
                     'legendEntries',   {{'method','coreMethod','formulation','M','N','f'}}, ...
                     'noXLoopPrms',     0); 

    options.xScale = 180/pi;
    figure(5)
    printResultsToTextFiles(study,options)
end