close all
for study_i = 1:numel(studies)
    study = studies(study_i);
    options = struct('xname',           'extraGP',  ...
                     'yname',           'surfaceError', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'semilogy', ... 
                     'lineStyle',       '*-', ... 
                     'xLoopName',       'extraGP', ...
                     'legendEntries',   {{'method','delta'}}, ...
                     'noXLoopPrms',     1); 

    figure(2)
    printResultsToTextFiles(study,options)
end
% close all
% for study_i = 1:numel(studies)  
%     study = studies(study_i);
%     options = struct('xname',           'alpha',  ...
%                      'yname',           'TS', ...
%                      'plotResults', 	1, ... 
%                      'printResults',	1, ... 
%                      'axisType',        'plot', ... 
%                      'lineStyle',       '-', ... 
%                      'subFolderName',   '../results/Cube', ...
%                      'legendEntries',   {{'method','coreMethod','formulation','M','degree'}}, ...
%                      'noXLoopPrms',     0); 
% 
%     options.xScale = 180/pi;
%     figure(4)
%     printResultsToTextFiles(study,options)
% end