
for study_i = 1:numel(studies)
    study = studies(study_i);
    options = struct('xname',           'colBEM_C0',  ...
                     'yname',           'surfaceError', ...
                     'plotResults', 	1, ... 
                     'printResults',	1, ... 
                     'axisType',        'loglog', ... 
                     'lineStyle',       '*-', ... 
                     'xLoopName',       'colBEM_C0', ...
                     'subFolderName',   '../results/Simpson_Torus_gp', ...
                     'legendEntries',   {{'method','coreMethod','formulation','degree','extraGP','extraGPBEM','agpBEM','useNeumanProj'}}, ...
                     'noXLoopPrms',     1); 

    figure(2)
    printResultsToTextFiles(study,options)
end
