
switch infiniteElementFormulation
    case 'PGU'
        temp2 = RR*(-2*k^2*chi^2*B1(nt+mt)-1i*k*chi*(nt+mt+2)*B1(nt+mt+1)+(mt*(nt+2)+k^2*Upsilon^2)*B1(nt+mt+2) ...
                   +1i*k*Upsilon^2/chi*(nt+mt+2)*B1(nt+mt+3)-mt*(nt+2)*Upsilon^2/chi^2*B1(nt+mt+4)+k^2*Upsilon^2*cos(theta)^2*B1(nt+mt+2) ...
                   +1/chi^2*(-k^2*chi^2-1i*k*chi*(nt+mt+2)+mt*(nt+2)) ...
                           *(dchidtheta^2*B1(nt+mt+2)+dchidphi^2/sin(theta)^2*(B2(nt+mt+1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+3)))) ...
               +(RtRt+RtR*dchidtheta*(-1i*k+mt/chi)+RRt*dchidtheta*(-1i*k+(nt+2)/chi))*B1(nt+mt+2) ...
               +RpRp/sin(theta)^2*(B2(nt+mt+1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+3)) ...
               +dchidphi/sin(theta)^2*(RpR*(-1i*k+mt/chi)+RRp*(-1i*k+(nt+2)/chi)) ...
                                     *(B2(nt+mt+1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+3));

%                         temp2 = RR*(-2*k^2*chi^2*B1(nt+mt)-1i*k*chi*(nt+mt+2)*B1(nt+mt+1)+(mt*(nt+2)+k^2*Upsilon^2)*B1(nt+mt+2) ...
%                                    +1i*k*Upsilon^2/chi*(nt+mt+2)*B1(nt+mt+3)-mt*(nt+2)*Upsilon^2/chi^2*B1(nt+mt+4)+k^2*Upsilon^2*cos(theta)^2*B1(nt+mt+2)) ...
%                                +RtRt*B1(nt+mt+2) ...
%                                +RpRp/sin(theta)^2*(B2(nt+mt+1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+3));

%                         temp2 = RR*(-k^2*chi^2*B1(nt+mt)-1i*k*chi*(nt+mt+2)*B1(nt+mt+1) ...
%                                     +mt*(nt+2)*B1(nt+mt+2)+k^2*Upsilon^2*B1(nt+mt+2) ...
%                                     +1i*k*Upsilon^2/chi*(nt+mt+2)*B1(nt+mt+3) - mt*(nt+2)*Upsilon^2/chi^2*B1(nt+mt+4)) ...
%                                 +RtRt*B1(nt+mt+2)+RtR*dchidtheta*(-1i*k*B1(nt+mt+2)+mt/chi*B1(nt+mt+2)) ...
%                                 +RRt*dchidtheta*(-1i*k*B1(nt+mt+2)+(nt+2)/chi*B1(nt+mt+2)) ...
%                                 +RR*dchidtheta^2*(-k^2*B1(nt+mt+2)-1i*k*(nt+mt+2)/chi*B1(nt+mt+2) ...
%                                                             +1/chi^2*mt*(nt+2)*B1(nt+mt+2)) ...
%                                 +1/sin(theta)^2*(RpRp*B2(nt+mt+1) ...
%                                                  +RpR*dchidphi*(-1i*k*B2(nt+mt+1)+mt/chi*B2(nt+mt+1)) ...
%                                                  +RpR*dchidphi*(-1i*k*B2(nt+mt+1)+(nt+2)/chi*B2(nt+mt+1)) ...
%                                                  +RR*dchidphi^2*(-k^2*B2(nt+mt+1)-1i*k*(mt+nt+2)/chi*B2(nt+mt+1) ...
%                                                                  +mt*(nt+2)/chi^2*B2(nt+mt+1))) ...
%                                 -Upsilon^2*cos(theta)^2/(chi^2*sin(theta)^2)*(RpRp*B2(nt+mt+3) ...
%                                                  +RpR*dchidphi*(-1i*k*B2(nt+mt+3)+mt/chi*B2(nt+mt+3)) ...
%                                                  +RpR*dchidphi*(-1i*k*B2(nt+mt+3)+(nt+2)/chi*B2(nt+mt+3)) ...
%                                                  +RR*dchidphi^2*(-k^2*B2(nt+mt+3)-1i*k*(mt+nt+2)/chi*B2(nt+mt+3) ...
%                                                                  +mt*(nt+2)/chi^2*B2(nt+mt+3)))...
%                                 -k^2*RR*(chi^2*B1(nt+mt)-Upsilon^2*cos(theta)^2*B1(nt+mt+2));

%                         temp2 = RR*(-k^2*(chi^2*B1(nt+mt)-Upsilon^2*B1(nt+mt+2)) ...
%                                     -(mt+nt+2)/chi*(chi^2*B1(nt+mt+1)-Upsilon^2*B1(nt+mt+3))*1i*k ...
%                                     +mt*(nt+2)/chi^2*(chi^2*B1(nt+mt+2)-Upsilon^2*B1(nt+mt+4))) ...
%                                 +RtRt*B1(nt+mt+2)+(RtR*(-1i*k+mt/chi)+RRt*(-1i*k+(nt+2)/chi))*dchidtheta*B1(nt+mt+2) ...
%                                 +RR*(-k^2-(mt+nt+2)/chi*1i*k+mt*(nt+2)/chi^2)*dchidtheta^2*B1(nt+mt+2) ...
%                                 +1/chi^2*1/sin(theta)^2*( RpRp+(RpR*(-1i*k+mt/chi)+RRp*(-1i*k+(nt+2)/chi))*dchidphi ...
%                                                          +RR*(-k^2-(mt+nt+2)/chi*1i*k+mt*(nt+2)/chi^2)*dchidphi^2)...
%                                                         *(chi^2*B2(nt+mt+1)-Upsilon^2*cos(theta)^2*B2(nt+mt+3)) ...
%                                 -k^2*(chi^2*B1(nt+mt)-Upsilon^2*cos(theta)^2*B1(nt+mt+2))*RR;

    case 'PGC'
        temp2 = RR*(-1i*k*chi*(nt-mt+2)*B1(nt+mt+1)+(mt*(nt+2)-k^2*Upsilon^2)*B1(nt+mt+2) ...
                   +1i*k*Upsilon^2/chi*(nt-mt+2)*B1(nt+mt+3)-mt*(nt+2)*Upsilon^2/chi^2*B1(nt+mt+4)+k^2*Upsilon^2*cos(theta)^2*B1(nt+mt+2) ...
                   +1/chi^2*(k^2*chi^2-1i*k*chi*(nt-mt+2)+mt*(nt+2)) ...
                           *(dchidtheta^2*B1(nt+mt+2)+dchidphi^2/sin(theta)^2*(B2(nt+mt+1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+3)))) ...
               +(RtRt+RtR*dchidtheta*(-1i*k+mt/chi)+RRt*dchidtheta*(1i*k+(nt+2)/chi))*B1(nt+mt+2) ...
               +RpRp/sin(theta)^2*(B2(nt+mt+1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+3)) ...
               +dchidphi/sin(theta)^2*(RpR*(-1i*k+mt/chi)+RRp*(1i*k+(nt+2)/chi)) ...
                                     *(B2(nt+mt+1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+3));
    case 'BGU'
        if mt+nt == 2
            temp2 = RR*(-2*1i*k*chi*B1(1)+(1+k^2*Upsilon^2)*B1(2) ...
                        +2*1i*k*Upsilon^2/chi*B1(3)-Upsilon^2/chi^2*B1(4)+k^2*Upsilon^2*cos(theta)^2*B1(2) ...
                        +1/chi^2*(-k^2*chi^2-2*1i*k*chi+1) ...
                           *(dchidtheta^2*B1(2)+dchidphi^2/sin(theta)^2*(B2(1)-Upsilon^2/chi^2*cos(theta)^2*B2(3))) ...
                        -1i*k*exp(2*1i*k*chi)*chi) ...
                    +(RtRt + RtR*dchidtheta*(-1i*k+1/chi)+RRt*dchidtheta*(-1i*k+1/chi))*B1(2) ...
                    +RpRp/sin(theta)^2*(B2(1)-Upsilon^2/chi^2*cos(theta)^2*B2(3)) ...
                    +dchidphi/sin(theta)^2*(RpR*(-1i*k+1/chi)+RRp*(-1i*k+1/chi)) ...
                                           *B2(1)-Upsilon^2/chi^2*cos(theta)^2*B2(3);
        else
            temp2 = RR*(-2*k^2*chi^2*B1(nt+mt-2)-1i*k*chi*(nt+mt)*B1(nt+mt-1)+(mt*nt+k^2*Upsilon^2)*B1(nt+mt) ...
                        +1i*k*Upsilon^2/chi*(nt+mt)*B1(nt+mt+1)-mt*nt*Upsilon^2/chi^2*B1(nt+mt+2)+k^2*Upsilon^2*cos(theta)^2*B1(nt+mt) ...
                        +1/chi^2*(-k^2*chi^2-1i*k*chi*(nt+mt)+mt*nt) ...
                                *(dchidtheta^2*B1(nt+mt)+dchidphi^2/sin(theta)^2*(B2(nt+mt-1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+1)))) ...
                    +(RtRt + RtR*dchidtheta*(-1i*k+mt/chi)+RRt*dchidtheta*(-1i*k+nt/chi))*B1(nt+mt) ...
                    +RpRp/sin(theta)^2*(B2(nt+mt-1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+1)) ...
                    +dchidphi/sin(theta)^2*(RpR*(-1i*k+mt/chi)+RRp*(-1i*k+nt/chi)) ...
                                           *B2(nt+mt-1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+1);
        end
    case 'BGC'
        if mt+nt == 2
            temp2 = RR*((1-k^2*Upsilon^2)*B1(2) ...
                       -Upsilon^2/chi^2*B1(4)+k^2*Upsilon^2*cos(theta)^2*B1(2) ...
                       +1/chi^2*(k^2*chi^2+1) ...
                                *(dchidtheta^2*B1(2)+dchidphi^2/sin(theta)^2*(B2(1)-Upsilon^2/chi^2*cos(theta)^2*B2(3))) ...
                        -1i*k*chi) ...
                   +(RtRt+RtR*dchidtheta*(-1i*k+1/chi)+RRt*dchidtheta*(1i*k+1/chi))*B1(2) ...
                   +RpRp/sin(theta)^2*(B2(1)-Upsilon^2/chi^2*cos(theta)^2*B2(3)) ...
                   +dchidphi/sin(theta)^2*(RpR*(-1i*k+1/chi)+RRp*(1i*k+1/chi)) ...
                                         *(B2(1)-Upsilon^2/chi^2*cos(theta)^2*B2(3));
        else
            temp2 = RR*(-1i*k*chi*(nt-mt)*B1(nt+mt-1)+(mt*nt-k^2*Upsilon^2)*B1(nt+mt) ...
                       +1i*k*Upsilon^2/chi*(nt-mt)*B1(nt+mt+1)-mt*nt*Upsilon^2/chi^2*B1(nt+mt+2)+k^2*Upsilon^2*cos(theta)^2*B1(nt+mt) ...
                       +1/chi^2*(k^2*chi^2-1i*k*chi*(nt-mt)+mt*nt) ...
                                *(dchidtheta^2*B1(nt+mt)+dchidphi^2/sin(theta)^2*(B2(nt+mt-1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+1)))) ...
                   +(RtRt+RtR*dchidtheta*(-1i*k+mt/chi)+RRt*dchidtheta*(1i*k+nt/chi))*B1(nt+mt) ...
                   +RpRp/sin(theta)^2*(B2(nt+mt-1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+1)) ...
                   +dchidphi/sin(theta)^2*(RpR*(-1i*k+mt/chi)+RRp*(1i*k+nt/chi)) ...
                                         *(B2(nt+mt-1)-Upsilon^2/chi^2*cos(theta)^2*B2(nt+mt+1));
        end
end